# Generated by Django 3.2.13 on 2022-11-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
