# Generated by Django 3.2.13 on 2022-11-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheers', '0003_auto_20221115_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cheers.user'),
            preserve_default=False,
        ),
    ]
