# Generated by Django 3.2.13 on 2022-11-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheers', '0010_auto_20221116_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
